// src/App.jsx
import {useEffect, useState} from 'react'
import './App.css'
import {NavBar, NavRail} from "./Navigation.jsx";
import Home from "./Home.jsx";
import Insert from "./Insert.jsx";
import Remove from "./Remove.jsx";
import Encode from "./Encode.jsx";
import Decode from "./Decode.jsx";

export default function App() {
    const [page, setPage] = useState("home");
    const [navType, setNavType] = useState("bar");
    const [darkTheme, setDarkTheme] = useState(false)
    useEffect(() => {
        if(window.screen.height < window.screen.width) { setNavType("rail") }
        setDarkTheme(window.matchMedia("(prefers-color-scheme: dark)").matches)
    }, [])
    document.getElementById("html_root").className = darkTheme ? "mdui-theme-dark" : "mdui-theme-light"
    let pageObj = <></>
    if(page === 'home') { pageObj = <Home darkTheme={darkTheme} setDarkTheme={(dark) => setDarkTheme(dark)}/> }
    if(page === 'insert') { pageObj = <Insert/> }
    if(page === 'remove') { pageObj = <Remove/> }
    if(page === 'encode') { pageObj = <Encode/> }
    if(page === 'decode') { pageObj = <Decode/> }
    let navObj = <></>
    if(navType === "bar") { navObj = <NavBar/> }
    if(navType === "rail") { navObj = <NavRail/> }
    window.onload = () => {
        if(navType === "bar") {
            const navbar = document.getElementById("navbar");
            navbar.addEventListener('change', () => setPage(navbar.value));
        } else {
            const navrail = document.getElementById("navrail");
            navrail.addEventListener('change', () => setPage(navrail.value));
        }
    }
    return (
        <>
            {pageObj}
            {navObj}
        </>
    )
}

// src/App.vue
<script setup lang="ts">
import { ref, onMounted, getCurrentInstance } from 'vue'
import NavBar from './NavBar.vue'
import NavRail from './NavRail.vue'
import Home from './Home.vue'
import Insert from './Insert.vue'
import Remove from './Remove.vue'
import Encode from './Encode.vue'
import Decode from './Decode.vue'
const instance = getCurrentInstance()!
const currentPage = ref('home')
var nav = ref('navbar')
document.getElementById('html')!.className = window.matchMedia("(prefers-color-scheme: dark)").matches? 'mdui-theme-dark': 'mdui-theme-light'
if(window.screen.height < window.screen.width) { nav.value = 'navrail' }
function switchPage() {
    currentPage.value = instance.refs[nav.value].$refs[nav.value].value
}
onMounted(()=>{
    instance.refs[nav.value].$refs[nav.value].addEventListener('change', switchPage)
})
</script>

<template>
    <Home v-if="currentPage=='home'" class="page" ref="home"/>
    <Insert v-if="currentPage=='insert'" class="page" ref="insert"/>
    <Remove v-if="currentPage=='remove'" class="page" ref="remove"/>
    <Encode v-if="currentPage=='encode'" class="page" ref="encode"/>
    <Decode v-if="currentPage=='decode'" class="page" ref="decode"/>
    <NavRail v-if="nav=='navrail'" ref="navrail"/>
    <NavBar v-if="nav=='navbar'" ref="navbar"/>
</template>

<style scoped>
.page {
    display: flex;
    flex-direction: column;
    align-items: center;
}
</style>
